project:
  type: website
  output-dir: docs

website:
  title: "MitoPilot Workshop 2025"
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - qmd/MitoPilot_intro/MitoPilot-intro.qmd
      - qmd/HPC_intro/HPC-intro.qmd
      - qmd/full_R_script/R-script.qmd
      - section: "Scripts"
        contents:
        - qmd/scripts/01_bash-script.qmd
        - qmd/scripts/02_R-script.qmd
      - section: "Setup"
        contents:
        - qmd/setup/01_Hydra.qmd
        - qmd/setup/02_RstudioServer.qmd
        - qmd/setup/03_RIntro.qmd
        - qmd/setup/04_install.qmd
        - qmd/setup/05_load.qmd
      - section: "Example Project"
        contents:
        - qmd/example_project/00_R-script.qmd
        - qmd/example_project/01_init.qmd
        - qmd/example_project/02_nextflow.qmd
        - qmd/example_project/03_asmb.qmd
        - qmd/example_project/04_annotation.qmd
        - qmd/example_project/05_export.qmd
      - section: "Starting Your Own Project"
        contents:
        - qmd/your_project/01_prep.qmd
        - qmd/your_project/02_init.qmd
      - section: "Advanced Usage"
        contents:
        - qmd/advanced/01_assemblyOpts.qmd
        - qmd/advanced/02_customAsmbDB.qmd
        - qmd/advanced/03_customCurationDB.qmd
        - qmd/advanced/04_customCurationRuleset.qmd
        - qmd/advanced/05_dbUpdate.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    mermaid:
      theme: default


